Adds basic styling to application

diff --git a/pre-push b/pre-push
--- a/pre-push
+++ b/pre-push
@@ -31,6 +31,13 @@ if [[ $rc != 0 ]] ; then
     exit $rc
 fi
 
+npm run lint:css
+rc=$?
+if [[ $rc != 0 ]] ; then
+    echo "${RED}Pre-push failed on CSS linting - please ensure you fix any linting errors before attempting to push again${CLEAR_COLOUR}"
+    exit $rc
+fi
+
 echo "${GREEN}pre-push script ran succesfully${CLEAR_COLOUR}"
 
 exit 0
