Modifies order of pre-push checks to run linters first

diff --git a/pre-push b/pre-push
--- a/pre-push
+++ b/pre-push
@@ -15,14 +15,6 @@ if [[ $rc != 0 ]] ; then
     exit $rc
 fi
 
-# Prevents push if tests fail
-CI=true npm run test
-rc=$?
-if [[ $rc != 0 ]] ; then
-    echo "${RED}Pre-push failed on tests - please ensure you fix any failing tests before attempting to push again${CLEAR_COLOUR}"
-    exit $rc
-fi
-
 # Prevents push if linter outputs errors or warning
 npm run lint -- --max-warnings 0
 rc=$?
@@ -35,6 +27,14 @@ npm run lint:css
 rc=$?
 if [[ $rc != 0 ]] ; then
     echo "${RED}Pre-push failed on CSS linting - please ensure you fix any linting errors before attempting to push again${CLEAR_COLOUR}"
+    exit $rc
+fi
+
+# Prevents push if tests fail
+CI=true npm run test
+rc=$?
+if [[ $rc != 0 ]] ; then
+    echo "${RED}Pre-push failed on tests - please ensure you fix any failing tests before attempting to push again${CLEAR_COLOUR}"
     exit $rc
 fi
 
